### ISSUE TITLE
Application fail to start without "jackson-databind" in depencencies

### ISSUE THREAD

**Issue by vienhx** [fonimus/spring-boot-ssh-shell#18]
I use gradle to build project, without **spring-boot-starter-web**, and without **jackson-databind** in dependencies, application fail to start with exception:

`Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_162]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[na:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_162]
	... 116 common frames omitted`

IMO, '**jackson-databind**' is a required dependency

**Comment by fonimus** [comment]
Fixed in 1.0.4, thank you for your feedback !
